// "use client"
// import { Inter } from "next/font/google";
// import "./globals.css";
// import MiniDrawer from "./Home/Sidebar/page";
// import { useRouter } from "next/navigation";

// const inter = Inter({ subsets: ["latin"] });

// export default function RootLayout({ children }) {
//   const router = useRouter();
//   const { pathname } = router;

//   // Only show MiniDrawer if the current path is not `/login`
//   const showSidebar = pathname !== '/login';

//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         {showSidebar ? <MiniDrawer>{children}</MiniDrawer> : children}
//       </body>
//     </html>
//   );
// }

import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}

